[mgr]
prepend_keymap = [
  { on = "e", run = "shell 'case \"$(file -b --mime-type %s)\" in image/*) pinta %s & ;; esac'", desc = "Edit image with pinta" },
  { on = "J", run = "arrow 5",  desc = "Move down 5" },
  { on = "K", run = "arrow -5", desc = "Move up 5" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter directory or open file" },

  # Go-to shortcuts
  { on = ["g", "h"], run = "cd ~",             desc = "Go to home" },
  { on = ["g", "d"], run = "cd ~/Downloads",    desc = "Go to Downloads" },
  { on = ["g", "c"], run = "cd ~/Documents",   desc = "Go to Documents" },
  { on = ["g", "s"], run = "cd ~/Screenshots", desc = "Go to Screenshots" },
  { on = ["g", "m"], run = "cd ~/Music",       desc = "Go to Music" },
  { on = ["g", "l"], run = "cd ~/Library",     desc = "Go to Library" },
  { on = ["g", "p"], run = "cd ~/Pictures",    desc = "Go to Pictures" },
  { on = ["g", "v"], run = "cd ~/Videos",      desc = "Go to Videos" },
]
