[mgr]
linemode = "size_and_info"

[[plugin.prepend_fetchers]]
id  = "ffmpeg_stats"
url = "*"
run = "ffmpeg-stats"

[[plugin.prepend_previewers]]
mime = "application/epub+zip"
run  = "epub"

[[plugin.prepend_previewers]]
mime = "application/msword"
run  = "office"

[[plugin.prepend_previewers]]
mime = "application/vnd.openxmlformats-officedocument.*"
run  = "office"

[[plugin.prepend_previewers]]
mime = "application/vnd.ms-*"
run  = "office"

[[plugin.prepend_previewers]]
mime = "application/vnd.oasis.opendocument.*"
run  = "office"

[preview]
image_quality = 90
max_width = 3000
max_height = 3000
