# Default colors
[colors.primary]
background = '#142838'
foreground = '#8ff586'

[colors.cursor]
text = '#122637'
cursor = '#c4206f'

[colors.selection]
text = "CellForeground"
background = "#084fb0"

# Normal colors
[colors.normal]
black   = '#142630'
red     = '#ff2320'
green   = '#3aa5ff'
yellow  = '#e9e75c'
blue    = '#8ff586'
magenta = '#781aa0'
cyan    = '#8ff586'
white   = '#ba45b1'

# Bright colors
[colors.bright]
black   = '#fff688'
red     = '#d4312e'
green   = '#8ff586'
yellow  = '#e9f06d'
blue    = '#3c7dd2'
magenta = '#8230a7'
cyan    = '#6cbc67'
white   = '#8ff586'

[font]
normal.family = "Universal"
size = 10.0

[cursor]
style = "Beam"
unfocused_hollow=false

[keyboard]

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"