#!/bin/zsh

$SCRIPTS_PATH/pritunl-install.sh
$SCRIPTS_PATH/qbittorrent-install.sh

$SCRIPTS_PATH/auto-yay.sh inotify-tools
$SCRIPTS_PATH/auto-yay.sh thunar
$SCRIPTS_PATH/auto-yay.sh rofi
$SCRIPTS_PATH/auto-yay.sh bluez
$SCRIPTS_PATH/auto-yay.sh bluez-utils
$SCRIPTS_PATH/auto-yay.sh brightnessctl
$SCRIPTS_PATH/auto-yay.sh copyq
$SCRIPTS_PATH/auto-yay.sh docker-compose
$SCRIPTS_PATH/auto-yay.sh gnome-keyring
$SCRIPTS_PATH/auto-yay.sh bitwarden-cli
$SCRIPTS_PATH/auto-yay.sh python-packaging
$SCRIPTS_PATH/auto-yay.sh gvfs
$SCRIPTS_PATH/auto-yay.sh p7zip
$SCRIPTS_PATH/auto-yay.sh dunst
$SCRIPTS_PATH/auto-yay.sh upower
$SCRIPTS_PATH/auto-yay.sh xclip
$SCRIPTS_PATH/auto-yay.sh cups
$SCRIPTS_PATH/auto-yay.sh ghostscript
$SCRIPTS_PATH/auto-yay.sh go
$SCRIPTS_PATH/auto-yay.sh hugo
$SCRIPTS_PATH/auto-yay.sh bind
$SCRIPTS_PATH/auto-yay.sh yt-dlp
$SCRIPTS_PATH/auto-yay.sh id3v2
$SCRIPTS_PATH/auto-yay.sh ttf-adobe-source-code-pro-fonts
$SCRIPTS_PATH/auto-yay.sh ttf-nerd-fonts-symbols
$SCRIPTS_PATH/auto-yay.sh ttf-font-awesome
$SCRIPTS_PATH/auto-yay.sh terraform
$SCRIPTS_PATH/auto-yay.sh aws-cli
$SCRIPTS_PATH/auto-yay.sh kubectl
$SCRIPTS_PATH/auto-yay.sh jq
$SCRIPTS_PATH/auto-yay.sh maim
$SCRIPTS_PATH/auto-yay.sh vlc
$SCRIPTS_PATH/auto-yay.sh bc
$SCRIPTS_PATH/auto-yay.sh eza
$SCRIPTS_PATH/auto-yay.sh upx
$SCRIPTS_PATH/auto-yay.sh vivaldi
$SCRIPTS_PATH/auto-yay.sh vivaldi-ffmpeg-codecs
$SCRIPTS_PATH/auto-yay.sh npm
$SCRIPTS_PATH/auto-yay.sh rclone
$SCRIPTS_PATH/auto-yay.sh qemu-full
$SCRIPTS_PATH/auto-yay.sh obsidian
$SCRIPTS_PATH/auto-yay.sh glab
$SCRIPTS_PATH/auto-yay.sh github-cli
$SCRIPTS_PATH/auto-yay.sh expac
$SCRIPTS_PATH/auto-yay.sh slack-desktop
$SCRIPTS_PATH/auto-yay.sh zoom
$SCRIPTS_PATH/auto-yay.sh mailspring
$SCRIPTS_PATH/auto-yay.sh beeper-latest-bin
$SCRIPTS_PATH/auto-yay.sh visual-studio-code-bin
$SCRIPTS_PATH/auto-yay.sh docker-desktop
$SCRIPTS_PATH/auto-yay.sh cloud-sql-proxy
$SCRIPTS_PATH/auto-yay.sh autokey-gtk
$SCRIPTS_PATH/auto-yay.sh autokey-common
$SCRIPTS_PATH/auto-yay.sh postman-bin
$SCRIPTS_PATH/auto-yay.sh adw-gtk3
$SCRIPTS_PATH/auto-yay.sh koodo-reader-bin
$SCRIPTS_PATH/auto-yay.sh google-cloud-cli
$SCRIPTS_PATH/auto-yay.sh google-cloud-cli-gke-gcloud-auth-plugin
$SCRIPTS_PATH/auto-yay.sh musescore-midi
$SCRIPTS_PATH/auto-yay.sh vault
$SCRIPTS_PATH/auto-yay.sh openvpn
$SCRIPTS_PATH/auto-yay.sh anki-bin
$SCRIPTS_PATH/auto-yay.sh fzf
$SCRIPTS_PATH/auto-yay.sh atuin-git
$SCRIPTS_PATH/auto-yay.sh mop
$SCRIPTS_PATH/auto-yay.sh lazydocker
