hyperctl dispatch moveworkspacetomonitor 1 eDP-1
hyperctl dispatch moveworkspacetomonitor 2 eDP-1
hyperctl dispatch moveworkspacetomonitor 3 eDP-1
hyperctl dispatch moveworkspacetomonitor 4 DP-3
hyperctl dispatch moveworkspacetomonitor 5 DP-3
hyperctl dispatch moveworkspacetomonitor 6 DP-3
hyperctl dispatch moveworkspacetomonitor 7 DP-3
hyperctl dispatch moveworkspacetomonitor 8 DP-4
hyperctl dispatch moveworkspacetomonitor 9 DP-4
hyperctl dispatch moveworkspacetomonitor 0 DP-4