source $SCRIPTS_PATH/battery.sh

get_battery_status 92 discharging
get_battery_status 83 discharging
get_battery_status 74 discharging
get_battery_status 65 discharging
get_battery_status 56 discharging
get_battery_status 47 discharging
get_battery_status 38 discharging
get_battery_status 29 discharging
get_battery_status 20 discharging
get_battery_status 11 discharging
get_battery_status 2 discharging
get_battery_status 2 charging

